In [8]:
x = [91, 106, 120, 100, 110, 125, 141, 152, 130, 140]
y = [186, 198, 220, 210, 190, 225, 258, 237, 230, 240]
sigma = 22.1
import numpy as np

# Square influence function
a = []
for i in range(len(x)):
    d = []
    for j in range(len(y)):
        if i == j:
            d.append(0.0)
        else:
            d.append(float(max(abs(x[j] - x[i]), abs(y[j] - y[i]))))
    a.append(d)
a = np.array(a)
print(a)
# Density function
density = []
for i in range(len(a)):
    temp = 0
    for j in range(len(a[i])):
        if a[i][j] > sigma:
            temp += 0
        else:
            temp += 1
    density.append(temp)
density = np.array(density)
            
# print(density)

[[ 0. 15. 34. 24. 19. 39. 72. 61. 44. 54.]
 [15.  0. 22. 12.  8. 27. 60. 46. 32. 42.]
 [34. 22.  0. 20. 30.  5. 38. 32. 10. 20.]
 [24. 12. 20.  0. 20. 25. 48. 52. 30. 40.]
 [19.  8. 30. 20.  0. 35. 68. 47. 40. 50.]
 [39. 27.  5. 25. 35.  0. 33. 27.  5. 15.]
 [72. 60. 38. 48. 68. 33.  0. 21. 28. 18.]
 [61. 46. 32. 52. 47. 27. 21.  0. 22. 12.]
 [44. 32. 10. 30. 40.  5. 28. 22.  0. 10.]
 [54. 42. 20. 40. 50. 15. 18. 12. 10.  0.]]


In [9]:
density

array([3, 5, 6, 4, 4, 4, 3, 4, 5, 6])

In [10]:
n = len(a)
n

10

In [11]:
def find_attractor(i):
    current = i
    while True:
        # find neighbors within sigma
        neighbors = np.where(a[current] <= sigma)[0]

        # get densities of neighbors

        print(neighbors, '-'*10)
        neighbor_dens = density[neighbors]

        # highest density among neighbors
        max_dens = neighbor_dens.max()

        # if current point already has max density → attractor reached
        if density[current] == max_dens:
            return current
        
        # otherwise move to neighbor with highest density
        # if several, just pick the first
        next_point = neighbors[np.argmax(neighbor_dens)]
        current = next_point


# compute attractor for each point
attractors = np.array([find_attractor(i) for i in range(n)])
print("Attractor index for each point:", attractors.tolist())

# ---------------------------
# Step 4 — Cluster formation
# Points with same attractor belong to same cluster.
# ---------------------------

# unique attractor points
unique_attr = np.unique(attractors)

# assign cluster labels 0,1,2...
cluster_map = {attr: idx for idx, attr in enumerate(unique_attr)}

# label of each point = cluster of its attractor
labels = np.array([cluster_map[a] for a in attractors])
print("Cluster labels:", labels.tolist())

[0 1 4] ----------
[0 1 2 3 4] ----------
[1 2 3 5 8 9] ----------
[0 1 2 3 4] ----------
[1 2 3 5 8 9] ----------
[1 2 3 5 8 9] ----------
[1 2 3 4] ----------
[1 2 3 5 8 9] ----------
[0 1 3 4] ----------
[0 1 2 3 4] ----------
[1 2 3 5 8 9] ----------
[2 5 8 9] ----------
[1 2 3 5 8 9] ----------
[6 7 9] ----------
[2 5 6 7 8 9] ----------
[6 7 8 9] ----------
[2 5 6 7 8 9] ----------
[2 5 7 8 9] ----------
[1 2 3 5 8 9] ----------
[2 5 6 7 8 9] ----------
Attractor index for each point: [2, 2, 2, 2, 2, 2, 9, 9, 2, 9]
Cluster labels: [0, 0, 0, 0, 0, 0, 1, 1, 0, 1]
